hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986"

[[files]]
file = "README.md"
hash = "753f134e1e5698acd3dec4e18963f711f78a038c3d65ddc565b244b3782fca9c"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "ef55a85f0905e41d93de2b7e53266d393bf58f43917d9b15ea8f66b757a5996d"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "c668b4ad565c58243a1e0eb71884b17c77ab2242d983075f12dc2666060709ba"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "564937e9bb15ddeb6741ce741a35486bc71b2a9a178d176b6107cfcb30747540"

[[files]]
file = "config/yosbr/options.txt"
hash = "2299e914f3c3570ea6d0720ce58078396ad21f730c8db3152ce27e9513c48cb5"

[[files]]
file = "config/yosbr/server.properties"
hash = "ac54fed0993a9ba3e350a4417951d21688b55d71c4b43a435b58e917aeeea961"

[[files]]
file = "mods/adventure-platform-mod.pw.toml"
hash = "16836308db916c76ba4b25d566c0651d98ec55c1f065dd00a21660db162065cb"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "49a33ac37445e3c08eb1a958b4f81f0c9ce356a8c08ace17e5df98e18558b4b1"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "ddc96b08f1a32a08edd9b8e34257b9a37ea9b3836ae4371e26f54c4ade4fe3f1"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "659f7b849f370718cc5216c3de0fdc4863391f9889d00ebd4ccef8274ee7026d"
metafile = true

[[files]]
file = "mods/async.pw.toml"
hash = "cd8f4196eb132f2a1ebb8098c311f2f9ebf60b850d8afedfd4eb8893a8a4e412"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "22c41917ad4c966fdd627f3a4d9c1cb55db4220a2c087ae5518589fcf3d0a74a"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "64badefe03082699f587274a31d1f0793583a4d88aac8ea2226162f80783fb52"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "b98e0aca52ce8d08ee8df7177886589511b8bca779af078a6ff4837e814bccf4"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3d24d58b2caf4fd73d76b2d734a1d06490994d5d38177376e6f5d8d9f8fb87e0"
metafile = true

[[files]]
file = "mods/dismount-entity.pw.toml"
hash = "000cca573d23a563a51cf4128092d424fdea24db9bb45e215c6a68508d8011b6"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/healing-campfire.pw.toml"
hash = "9b85ab571026d3cf1d1c714c86335d6baf93c850f083c779c173cd2bf3ffca9b"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "bdca3c9a098de3c08f996b214cf10ece27351f5f7871c30ff826a2f404daba33"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2fb4ce2695c9f6da2087a5e350f2e85ea419de153e18bc20bf38f0b540c7caba"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ed9d0d5d4078c137900006321d35515cee46058b92df1128ea37cda3e5e1bb2b"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "ffd2bde70110ba1d26bf841930556307a5bdfa3159b194e6e30ac5192be61754"
metafile = true

[[files]]
file = "mods/monsters-in-the-closet.pw.toml"
hash = "1ba8624e6fdea849e4cd5acccd5e31e9b5bd162b07b6a3aca0cdb0a55b34d136"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "22a83a04b4df87ab4bbea18228c3cc695551610c66cc79ccc315d783d3f7848f"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "42a73228a2e7ddd0a2ebba1e2a03dec5dbf4605854ec89c05f7e1374baffeae5"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "a112d883056e0934ca5f7d8718f5a2c5cf9d6d63ecb7e91754ba9dcee7bb799e"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cdde1ed66709cde0656be902a1109532f255fd1526991acebe91116a4ab399df"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "b97b297fab12e137c58874ae776402cfa29374c8ff50c9f18ef27442b65336e6"
metafile = true

[[files]]
file = "mods/tool-trims.pw.toml"
hash = "e95c3632595162ddc8c48188979f19ef47c1965f36c9acc7be0f296d39c7ffa2"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
hash = "d039768c39de4e27eb317c590dc65e16b5c9afddd402089227617a03f58a9db4"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "ed9329edc09aae7041d14e6f68563b9235a10163e4fc9e4e31d5a2d81883845e"
metafile = true

[[files]]
file = "mods/vanilla-refresh.pw.toml"
hash = "c747d8ec64328f2722166ac62ea371cd5becf82fa4b8012a679092649046f5b4"
metafile = true

[[files]]
file = "mods/villager-names-serilum.pw.toml"
hash = "8cd9cfc9000cde17d56cebb2c3f19e3a106428c082436d53f72fc478ecc10037"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "bddb759a3929a93eff8ef2d36acfb7a45b455183c6d2019b346347767a335ce4"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f82809b1d8eaab731b217b01589ab13e1374c4d422f18640ba3262b55f3b4cfa"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true
