name = "A2K-FLOWERPOT-SERVER"
author = "A2KLAB"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccf4cdaf74f1e080c3877746ed832428c7ae5cdec340bbcbe969d59524445abe"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"
